### ISSUE TITLE
2.0.0 checklist

### ISSUE THREAD

**Issue by tomwayson** [Esri/hub.js#158]
- [ ] drop `@esri/hub-domains` (see below)
- [ ] drop [fetchDomain() & fetchDomains()](https://github.com/Esri/hub.js/pull/68)
- [ ] drop support for [adds in addAnnotations()](https://github.com/Esri/hub.js/blob/b336f324b1639993309ead0c87f91b13f737d97e/packages/annotations/src/add.ts#L55-L58) - how come we don't have to do this for other CRUD methods

re: `-domains` - the one fn in there has been deprecated in favor of a new fn in common. Unless @dbouwman  had grand plans to put stuff in there that doesn't belong in `@esri/hub-sites`:

<img width="320" alt="image" src="https://user-images.githubusercontent.com/662944/56745803-e420f600-672f-11e9-9ba9-3ed5ced813bc.png">

**Comment by jgravois** [comment]
> drop support for adds in addAnnotations()

i already got to this one in #156 

> how come we don't have to do this for other CRUD methods

that is a _good_ question.

**Comment by dbouwman** [comment]
I have no such plans... kill as you must @tomwayson

**Comment by jgravois** [comment]
resolved via b13a1c7

**Comment by tomwayson** [comment]
- [ ] remove JSON API response format from events
- [ ] remove JSON API response format from annotations
